### ISSUE TITLE
valueError: substring not found

### ISSUE THREAD

**Issue by vivianllii** [imyuka/TripAdvisor-Crawling-Suite#4]
<img width="472" alt="截屏2020-06-23下午3 42 28" src="https://user-images.githubusercontent.com/50654615/85358552-26c6a400-b568-11ea-938a-e46a1ffb5017.png">

we found errors in the crawlSnippets, but we don't know how to fix it;
Could you pls help us~

**Comment by tokawah** [comment]
Dear Vivian,

Thank you for showing your interest in the repository. The current suite no longer works as TripAdvisor has changed its website layout. Still, most of the code used is applicable to the crawling procedure. There is another piece of code (please see the link below) that currently works for collecting restaurant information from TripAdvisor. I hope that can give you some inspiration. Thank you.

https://github.com/tokawah/Location-based-Social-Networks/blob/master/TripAdvisor%20Restaurants%20Collection.ipynb
